### ISSUE TITLE
网易云音乐歌单和电台列表可否再细分类？

### ISSUE THREAD

**Issue by GuoJohnny** [Yaoshicn/awesome-music-for-programming#6]
比如：网易云音乐歌单下细分：

－－网易云音乐歌单
－－－－纯音乐
－－－－摇滚
－－－－流行
－－－－电影原声
－－－－背景音乐
－－－－....

－－网易云音乐电台
－－－－有声读物
－－－－音乐电台
－－－－－－EDM
－－－－－－纯音乐
－－－－－－...
－－－－人文历史
－－－－娱乐影视

目前歌单较少还可以一个个找个人喜爱的类别，当歌单多了会不会变得繁杂？是否需要再细分类？

**Comment by Yaoshicn** [comment]
首先感谢大家的分享和关注，但是也碰到一些问题，我在这儿总结一下。
# 关于学习工作的时候听不听音乐的问题
这个 repo 里不只有音乐，还列出了一些提供白噪音等的网站。与其说是分享音乐，不如说是分享音频更加符合这个 repo 的主旨。

# 分类问题
听音乐算是一个比较私人的事情，这个 repo 只提供一个参考，具体还是看个人口味。所以，如果您愿意的话，可以加入到分享的队伍中来，万一有和您口味相同的人呢？

# 添加项目并不在现有分类中
直接添加对应的分类，然后 pull requests 即可，我会及时 merge 并整理的。

最后，再次感谢大家的支持和分享！

**Comment by GuoJohnny** [comment]
分类能否再细分的问题？

**Comment by Yaoshicn** [comment]
提交时直接添加对应分类就行了……

**Comment by GuoJohnny** [comment]
了解～

**Comment by GuoJohnny** [comment]
了解～
